--outer join 
    SELECT 
    m.MODULE_CODE,
    m.MODULE_NAME,
    a.VENUE_CODE,
    a.ASSESSMENT_DATE
FROM MODULES m
FULL OUTER JOIN ASSESSMENT_BOOKING a 
    ON m.MODULE_CODE = a.MODULE_CODE;

    --left join 
    SELECT 
    m.MODULE_CODE,
    m.MODULE_NAME,
    a.VENUE_CODE,
    a.ASSESSMENT_DATE
FROM MODULES m
LEFT JOIN ASSESSMENT_BOOKING a 
    ON m.MODULE_CODE = a.MODULE_CODE;

    --right join 
    SELECT 
    v.VENUE_CODE,
    v.VENUE_NAME,
    v.CITY,
    a.MODULE_CODE,
    a.ASSESSMENT_DATE
FROM ASSESSMENT_BOOKING a
RIGHT JOIN VENUES v 
    ON a.VENUE_CODE = v.VENUE_CODE;
